# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Huy Nguyen
name: Huy Nguyen
position: Ph.D. Researcher
email: huy.nguyenhuu.hust@gmail.com
description: >-
  I am a Ph.D. researcher specializing in the systems-level architecture and distributed acceleration of Large Language Models (LLMs). My work focuses on pushing the physical limits of hardware utilization, from bare-metal CUDA/Cutlass kernel engineering, to designing topology-aware 5D parallel training engines. I build the underlying computational and cross-GPU interconnect infrastructure required to eliminate network bubbles and compute bottlenecks at massive scale.


  Prior to this, I completed my B.S. in Computer Science at [Hanoi University of Science and Technology](https://hust.edu.vn/) with an Excellent Degree (GPA 3.71/4.0), advised by [Dr. Linh Ngo Van](https://users.soict.hust.edu.vn/linhnv/).
  
  
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://huynguyen-hust.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: huynguyen_hust
github_username: HuyNguyen-hust
google_scholar: LAvXOdUAAAAJ

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/