# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Chien Nguyen
name: Chien Nguyen
position: Research Resident 
email: chiennv.hust@gmail.com
description: >-
  I graduated from [Hanoi University of Science and Technology](https://hust.edu.vn/) with a Computer Science Bachelor’s degree and was advised by [Dr. Linh Ngo Van](https://users.soict.hust.edu.vn/linhnv/).
  Currently, I am a Research Resident at [VinAI Research](https://vinai.io), Natural Language Processing group, under the supervision of [Prof. Thien Huu Nguyen](https://ix.cs.uoregon.edu/~thien/).



  My Research Interests focus on Machine Learning, Natural Language Processing and their intersection.
  I have experience on Information Extraction tasks in different domains and languages.
  I am currently engaged in Large Language Models (LLMs) and its application in NLP tasks.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chiennv2000.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: chiennv2000
github_username: chiennv2000
google_scholar: fW5HEnEAAAAJ

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/